### ISSUE TITLE
Data source issue

### ISSUE THREAD

**Issue by signing-suntans0y** [iamrony777/javinfo-api#11]
It seems like javdb and javlibrary are now working anymore.

Exception in request module, requests.raise_for_status()
404 Client Error: Not Found for url: https://javinfo-api.herokuapp.com/api/public?name=ssis-386&provider=javdb

**Comment by iamrony777** [comment]
Cloudflare issue, closing
Self-hosted docker container / Railway works fine

**Comment by iamrony777** [comment]
Fixed!
