### ISSUE TITLE
401 Unauthorized {"detail":"Access Denied"}

### ISSUE THREAD

**Issue by satirovaf** [iamrony777/javinfo-api#19]
Hey,

I've configured the .env file API username and password, and build the docker using docker-compose, but when using with CURL, passing the API and username and password, I receive the following error:

{"detail":"Access Denied"}

Any suggestion on what can be wrong? I tried to rebuild and reset the .env file, but the same error occurs.

Thanks in advance

**Comment by iamrony777** [comment]
I suggest checking _.env_ file again. _API_PASS_ comes before _API_USER_ so that may have caused confusion.
