### ISSUE TITLE
API not updated

### ISSUE THREAD

**Issue by lucius100** [iamrony777/JavInfo-api#26]
I think there's some structure changed on the website that cause some functions of the scraper fails, for now I only use /search to do the api request, the other not tested yet.

javlibrary working fine but no screenshots scraped.

javdb all function is working

javdatabase and r18 not working at all, even though the jav code is valid on the site, it said not found on the logs contain a lot of none type error. I also provided login on the environment , javdatabase still failed.

**Comment by iamrony777** [comment]
Could you please provide logs/screenshots of the errors? I'll look into this. Additionally, could you confirm if you are on branch 'v3'? If not, please switch to branch 'v3' only, as the previous scrapers are returning errors and are not efficient.

**Comment by lucius100** [comment]
> Could you please provide logs/screenshots of the errors? I'll look into this. Additionally, could you confirm if you are on branch 'v3'? If not, please switch to branch 'v3' only, as the previous scrapers are returning errors and are not efficient.

I already try redownload multiple times, I clone the repo directly 
git clone https://github.com/iamrony777/javinfo-api.git 

so I am sure it's the latest v3 , below is the error log, don't know why it still request data from dead r18.com, although I can see that in providers/r18.py already used r18.dev

[_javinfo-api_logs.txt](https://github.com/iamrony777/javinfo-api/files/13332639/_javinfo-api_logs.txt)


r18 response code

https://i.postimg.cc/0yCr7QFb/image.png

javlibrary response code

```
{
  "id": "EBOD-391",
  "title": "Breast Milk Real Gal Married Emma NozomiSaki",
  "poster": "https:https://pics.dmm.co.jp/mono/movie/adult/ebod391/ebod391pl.jpg",
  "page": "https://www.javlibrary.com/en/?v=javlijzd7i",
  "details": {
    "director": "Minami★Haou",
    "release_date": "2014-08-13",
    "runtime": "120",
    "studio": "E-BODY",
    "user_rating": "8.00"
  },
  "actress": [
    {
      "name": "Ema Kisaki",
      "image": "https://www.boobpedia.com/wiki/images/6/64/Ema_Kisaki.jpg",
      "also_known_as": "Haruki Kato, HARUKI",
      "born": "1989-08-30",
      "measurements": "95-62-89cm",
      "cup_size": "G",
      "boob_type": "Enhanced"
    }
  ],
  "screenshots": [],
  "tags": [
    "Solowork",
    "Gal",
    "Big Tits",
    "Breast Milk",
    "Nasty, Hardcore",
    "Slender"
  ]
}
```

**Comment by iamrony777** [comment]
From the logs I can confirm you aren't using v3 branch. And also this response structure is from previous versions

check the output of `git branch --show`, it should return `v3`


Expected Logs with installation process:
![image](https://github.com/iamrony777/javinfo-api/assets/88942925/b5154908-1c57-40e4-a113-6cd7e068c09b)


Expected output of `/search?code=EBOD-391`
```json
{
  "id": "EBOD-391",
  "title": "Real Breast Milk Married Woman - Ema Kisaki",
  "title_ja": null,
  "page": "https://javdatabase.com/movies/ebod-391/",
  "poster": "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391pl.jpg",
  "preview": null,
  "details": {
    "director": "Hao * Minami",
    "release_date": "2014-08-09",
    "runtime": "119",
    "studio": "E-BODY"
  },
  "actress": [
    {
      "name": "Ema Kisaki (HARUKI",
      "image": "https://www.javdatabase.com/idolimages/thumb/ema-kisaki-haruki.webp"
    },
    {
      "name": "Haruki Kato",
      "image": "https://www.javdatabase.com/idolimages/thumb/haruki-kato.webp"
    }
  ],
  "screenshots": [
    "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-1.jpg",
    "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-2.jpg",
    "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-3.jpg",
    "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-4.jpg",
    "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-5.jpg",
    "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-6.jpg"
  ],
  "tags": [
    "Big Tits",
    "Breast Milk",
    "Featured Actress",
    "Gal",
    "Hi-Def",
    "Nymphomaniac",
    "Slender"
  ]
}
```

**Comment by lucius100** [comment]
> From the logs I can confirm you aren't using v3 branch. And also this response structure is from previous versions
> 
> check the output of `git branch --show`, it should return `v3`
> 
> Expected Logs with installation process: ![image](https://user-images.githubusercontent.com/88942925/282409377-b5154908-1c57-40e4-a113-6cd7e068c09b.png)
> 
> Expected output of `/search?code=EBOD-391`
> 
> ```json
> {
>   "id": "EBOD-391",
>   "title": "Real Breast Milk Married Woman - Ema Kisaki",
>   "title_ja": null,
>   "page": "https://javdatabase.com/movies/ebod-391/",
>   "poster": "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391pl.jpg",
>   "preview": null,
>   "details": {
>     "director": "Hao * Minami",
>     "release_date": "2014-08-09",
>     "runtime": "119",
>     "studio": "E-BODY"
>   },
>   "actress": [
>     {
>       "name": "Ema Kisaki (HARUKI",
>       "image": "https://www.javdatabase.com/idolimages/thumb/ema-kisaki-haruki.webp"
>     },
>     {
>       "name": "Haruki Kato",
>       "image": "https://www.javdatabase.com/idolimages/thumb/haruki-kato.webp"
>     }
>   ],
>   "screenshots": [
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-1.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-2.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-3.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-4.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-5.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-6.jpg"
>   ],
>   "tags": [
>     "Big Tits",
>     "Breast Milk",
>     "Featured Actress",
>     "Gal",
>     "Hi-Def",
>     "Nymphomaniac",
>     "Slender"
>   ]
> }
> ```

![image](https://github.com/iamrony777/javinfo-api/assets/24198882/aaee662a-4d29-4a6e-b016-da09adaf1d13)

**Comment by iamrony777** [comment]
Now that's strange
what's the output of `ls -l` from top dir

Expected:
![image](https://github.com/iamrony777/javinfo-api/assets/88942925/e44be6fb-3310-4738-af31-5c69357f4f5f)

**Comment by lucius100** [comment]
> From the logs I can confirm you aren't using v3 branch. And also this response structure is from previous versions
> 
> check the output of `git branch --show`, it should return `v3`
> 
> Expected Logs with installation process: ![image](https://user-images.githubusercontent.com/88942925/282409377-b5154908-1c57-40e4-a113-6cd7e068c09b.png)
> 
> Expected output of `/search?code=EBOD-391`
> 
> ```json
> {
>   "id": "EBOD-391",
>   "title": "Real Breast Milk Married Woman - Ema Kisaki",
>   "title_ja": null,
>   "page": "https://javdatabase.com/movies/ebod-391/",
>   "poster": "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391pl.jpg",
>   "preview": null,
>   "details": {
>     "director": "Hao * Minami",
>     "release_date": "2014-08-09",
>     "runtime": "119",
>     "studio": "E-BODY"
>   },
>   "actress": [
>     {
>       "name": "Ema Kisaki (HARUKI",
>       "image": "https://www.javdatabase.com/idolimages/thumb/ema-kisaki-haruki.webp"
>     },
>     {
>       "name": "Haruki Kato",
>       "image": "https://www.javdatabase.com/idolimages/thumb/haruki-kato.webp"
>     }
>   ],
>   "screenshots": [
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-1.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-2.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-3.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-4.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-5.jpg",
>     "https://pics.dmm.co.jp/digital/video/ebod00391/ebod00391jp-6.jpg"
>   ],
>   "tags": [
>     "Big Tits",
>     "Breast Milk",
>     "Featured Actress",
>     "Gal",
>     "Hi-Def",
>     "Nymphomaniac",
>     "Slender"
>   ]
> }
> ```

Okay, I actually tried one more time, by doing the same steps like yours, but on my side, I got it up running and it also shows uvicorn running on https://127.0.0.1:3000 

but I can't access the main page at all, show 502 bad gateway, do you have other environment variables setup there ?
how about redis? database ?

the way I use it actually deploy using docker compose from this tutorial 

https://ronit.is-a.dev/javinfo-api/v1/deploy/docker/#building-docker-images

wget https://raw.githubusercontent.com/iamrony777/javinfo-api/main/docker-compose.yml
wget https://raw.githubusercontent.com/iamrony777/javinfo-api/main/.env.sample -O ".env"

I check the image inside docker-compose, doesn't this also the latest v3?

```
version: "3.8"

services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.build
    #   args:
    #     - CREATE_REDIS
    #     - PLATFORM
    image: iamrony777/javinfo-api:server
    container_name: javinfo-api
    environment:
      - "BASE_URL=http://127.0.0.1:${PORT}"
      - "INACTIVITY_TIMEOUT=60"
      - "HEALTHCHECK_PROVIDER=self"
      - "REDIS_URL=redis://default:${API_PASS}@db"
    env_file: 
      - .env
    ports:
      - "0.0.0.0:8000:${PORT}"
    depends_on:
      - db
    networks:
      - net
```

**Comment by lucius100** [comment]
> Now that's strange what's the output of `ls -l` from top dir
> 
> Expected: ![image](https://user-images.githubusercontent.com/88942925/282410987-e44be6fb-3310-4738-af31-5c69357f4f5f.png)

I know what's wrong now, the latest doesn't work for me. All setup and no error in the logs, but after navigate to the site at port 3000, nothing happen, got 503 error gateway

only the old one working for me by using docker compose

wget https://raw.githubusercontent.com/iamrony777/javinfo-api/main/docker-compose.yml
wget https://raw.githubusercontent.com/iamrony777/javinfo-api/main/.env.sample -O ".env"

no wonder I keep having old version. I will just wait until the latest got pushed into the docker hub image, the old one still using this version 

    image: iamrony777/javinfo-api:server
    
    
    
 Edit: I tried cyclic and managed to get it up, guess I am too dumb to setup my own in my vps, Now I can see only javdatabase supported in v3.

**Comment by iamrony777** [comment]
No issues, and v3 supports all 3 provider, but returns the fastest response. In future I'll add a provider parameter like previous version.

I'll stick to serverless (fast and free)

Closing this issue now
