### ISSUE TITLE
Add javdb provider

### ISSUE THREAD

**Issue by lucius100** [iamrony777/JavInfo-api#27]
Hello, can you add new provider javdb ?
We have 4 version in the old apis, and many series only found on javdb.

Btw, I also curious on what happen if we set providers to all, and the series only found in r18, but not on jvdtbs and jvlib, will it show as 404 error or return successful response ?

**Comment by iamrony777** [comment]
1. Yup, i'll add javdb provider soon
2. api will return successful response
