### ISSUE TITLE
jvlib (javlibrary) - Error: response status is 404

### ISSUE THREAD

**Issue by hvNewbieTools** [iamrony777/JavInfo-api#32]
Recently, any request from jvlib began to return a 404 error, despite the fact that the site itself is working and the page exists

**Comment by iamrony777** [comment]
Sorry for the late reply, I'm looking into this issue now

Update: Its a cloudflare issue, as they are blocking requests. Solution is to use selenium with undetected_chromedriver or use proxy. I'll go with proxy which will be added as an `.env` option, I'll recommend to host the app and use paid proxy 

Update: I recommend to set providers to `all`
