### ISSUE TITLE
Add Priority List for provider

### ISSUE THREAD

**Issue by lucius100** [iamrony777/JavInfo-api#33]
Can we add priority list to the provider ?
I mean the order of scraping, instead of get data from the fastest provider, it will search the priority provider
for example
It will go first from r18-javdb-javdatabase-javlibrary in the way we arrange / setting the priority, because each site has different category / tags, make the data seems complicated

it will search first from r18, if no result it goes to javdb, then the next, not just random scraping the fastest.

**Comment by iamrony777** [comment]
> it will search first from r18, if no result it goes to javdb, then the next, not just random scraping the fastest.

This approach will increase response time, but instead of prioritizing requests, I think I can prioritize responses. For example, fetch all responses at once, then return the result according to priority.
