### ISSUE TITLE
I got error running the latest build docker

### ISSUE THREAD

**Issue by lucius100** [iamrony777/JavInfo-api#34]
Traceback (most recent call last):
  File "/app/app.py", line 7, in <module>
    from src.routes import jav, non_jav, rss
  File "/app/src/__init__.py", line 16, in <module>
    javdbProvider = Javdb()
                    ^^^^^^^
  File "/app/src/providers/javdb.py", line 45, in __init__
    "remember_me_token": quote(getenv("REMEMBER_ME_TOKEN")),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 907, in quote
    return quote_from_bytes(string, safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 937, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

Any Idea ?
And it seems like javdtbs having issues, the script keep hanging when searching this provider
javdb always return no result
javlib don't bother to try anymore without proxy, the working one right now only r18
looks like they tried to block scraper now.

**Comment by iamrony777** [comment]
https://github.com/iamrony777/javinfo-api/blob/v3/SETUP.md#javdbcom-cookies

**Comment by lucius100** [comment]
> https://github.com/iamrony777/javinfo-api/blob/v3/SETUP.md#javdbcom-cookies

It's not the problem with cookies, did u try it already ? 
Did it work on your side ?
I also added the cookies but got error forbidden

**Comment by EnKuldes** [comment]
> > https://github.com/iamrony777/javinfo-api/blob/v3/SETUP.md#javdbcom-cookies
> 
> It's not the problem with cookies, did u try it already ? Did it work on your side ? I also added the cookies but got error forbidden

based on this [stackoverflow](https://stackoverflow.com/questions/55078654/troubelshooting-raise-typeerrorquote-from-bytes-expected-bytes), I think you need to add `str` function to this 2 lines at `src/providers/javdb.py`

![image](https://github.com/iamrony777/javinfo-api/assets/55388707/8df595aa-48e7-4ba9-bf26-079306db812f)
